#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib", "$FindBin::Bin/../extlib", "$FindBin::Bin/../plugins/MTObjectImporter/lib";

use MTObjectImporter::Tool;
MTObjectImporter::Tool->main;
